print("Welcome to this program that generates a stupid name for your band!")
city = input("Which city were you born in?\n")
pet = input("What is the name of your favorite pet?\n")
print("\nThe name of your band could be " + city + ' ' + pet)
print(f"And your band initials are: '{city[0]}. {pet[0]}'")
